#Source files
SRC=runner.c symbolTable.c types.c errors.c
TEST_SRC=$(filter-out runner.c, $(SRC))
TESTS= cunit/tests.c \
	cunit/symbolTableTests.c
#Autogenerated files
GEN=lex.yy.c y.tab.c
#Additional dependencies
DEP=					

# OS identification from: https://stackoverflow.com/questions/714100/os-detecting-makefile
OS := $(shell uname -s)

ifeq ($(OS), Darwin) 
  CUNIT_PATH_PREFIX = /usr/local/Cellar/cunit/2.1-3/
  CUNIT_DIRECTORY = cunit
endif

ifeq ($(OS), Linux) 
  CUNIT_PATH_PREFIX = /util/CUnit/
  CUNIT_DIRECTORY = CUnit/
endif

ifeq ($(OS), CYGWIN_NT-10.0) 
  CUNIT_PATH_PREFIX = /usr/
  CUNIT_DIRECTORY = CUnit/
endif

all: compiler_tools $(SRC)
	gcc -g -o compiler $(SRC) $(GEN) -Wall

compiler_tools: syntax_analayzer lexical_analyzer

lexical_analyzer: lexicalStructure.lex y.tab.h
	flex lexicalStructure.lex

syntax_analayzer: grammar.y
	yacc -d -v grammar.y

tests: $(TEST_SRC) $(TESTS)
	$(CC) $(CFLAGS) -lm -L $(CUNIT_PATH_PREFIX)lib -I $(CUNIT_PATH_PREFIX)include/$(CUNIT_DIRECTORY) -g $^ -o tests -lcunit -lgcov 

clean:
	rm -f $(GEN) compiler tests
