

#Source files
SRC=runner.c
#Autogenerated files
GEN=lex.yy.c
#Additional dependencies
DEP=					

all: compiler_tools $(SRC)
	gcc -o compiler $(SRC) $(GEN) -Wall

compiler_tools: syntax_analayzer lexical_analyzer

lexical_analyzer: lexicalStructure.lex y.tab.h
	flex lexicalStructure.lex

syntax_analayzer: grammar.y
	yacc -d grammar.y

clean:
	rm -f $(GEN) compiler
